"""messages.active_skills

Revision ID: 917df7461cf1
Revises: f7df6c5fafad
Create Date: 2026-05-27 22:49:25.990315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '917df7461cf1'
down_revision: Union[str, Sequence[str], None] = 'f7df6c5fafad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
        'messages',
        sa.Column(
            'active_skills',
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'[]'::jsonb"),
        ),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'active_skills')
    # ### end Alembic commands ###
